### ISSUE TITLE
Couldn't load map

### ISSUE THREAD

**Issue by Chris92de** [BigBang1112/nations-converter#11] opened 2020-12-12 04:28 UTC
Hey, I tried to convert a Stadium map made in TM Nations ESWC.
The conversion seems to be successful, but trying to load the map ingame says "Couldn't load map!"

I've attached the map so you can try and debug it yourself.

[CubanSalsa_255426.Challenge.zip](https://github.com/BigBang1112/nations-converter/files/5682490/CubanSalsa_255426.Challenge.zip)

**Comment by renefreund** [comment] 2020-12-12 05:02
@Chris92de i tried it with many tmnf or tm2 maps. same result. (v1.0.0)

seems only a subset of maps are doing great.

greetings

**Comment by BigBang1112** [comment] 2020-12-15 21:52
7cc2a85b4ac82d9736b5621eb786c05780db81ea The issue has been fixed for ESWC maps, TM2 maps still struggle to load.

**Comment by BigBang1112** [comment] 2020-12-15 22:26
7330799894f3f1687a2dd72dec55d461dfafebed TM2 issue was fixed as well and was caused by game/player camera mediatracker block, which will be temporarily removed in 1.1.0 and fixed in 1.1.1. I'm closing this issue for now until another "Couldn't load map" comes in.

**Comment by BigBang1112** [comment] 2021-05-06 15:15
There are still some pending issues with "Couldn't load map", so I'm reopening the issue.

**Comment by BigBang1112** [comment] 2022-02-21 11:57
Closing the issue due to upcoming rewrite plans.

**Closed by BigBang1112** 2022-02-21 11:57 UTC
